### ISSUE TITLE
IMG_Load 컴파일 에러 (실습06)

### ISSUE THREAD

**Issue by wawworld72** [wawworld72/gf-2019-02#2]
오류 메시지, 스샷 링크 등을 업로드

**Comment by kas9786** [comment]
실습 06

IMG_Load 사용 불가 에러

![Img](https://user-images.githubusercontent.com/54612439/65430212-86b1e200-de52-11e9-8ed6-7f9995c85caa.PNG)


해결방법 

#include <SDL_image.h>을 헤더파일에 추가

**Comment by wawworld72** [comment]
자신이 문제를 올리고 스스로 해결한거네.. 

질문만 올려도 된다.

대답은 다른 사람들이 올려줄거다.
