### ISSUE TITLE
실습 7

### ISSUE THREAD

**Issue by agaetis-byrjun** [wawworld72/gf-2019-02#5]
![오류1](https://user-images.githubusercontent.com/54656130/65987051-0fb6c200-e4c0-11e9-8965-84b6c75342dd.PNG)
![캡처2](https://user-images.githubusercontent.com/54656130/65987053-0fb6c200-e4c0-11e9-9f53-fea4ed1e3bb4.PNG)

헤더파일이 빠진것 같지 않은데 그렇다고 접근지정자가 이상한것 같지는 않은데 무었때문에 아예 받아들이지를 못하나요?

**Comment by AppleMangoSpd** [comment]
TextureManager.h에서 클래스 이름이 TextureManger로 되있어서 생기는 오류입니다.
클래스 이름을 수정하시면 정상적으로 작동 할 것 같아요.
